### PR TITLE
Add support for Monitoring Agent Tokens

### PR DESCRIPTION
**Pull request by rs-randallburt**
Added support to the monitoring client for managing agent tokens

### CODE REVIEW

**Comment by rs-randallburt** [comment]
Script for verification if you need it: https://gist.github.com/rs-randallburt/efc67421a704445a616b

**Comment by sivel** [comment]
This PR now contains a merge conflict.  Would you mind updating?  Please remember to squash after the update.

**Comment by rs-randallburt** [comment]
Rebased.

**Comment by sivel** [comment]
Merged, thanks!

**Pull request merged**
