### PR TITLE
Swap support email address for support URL

### PR DESCRIPTION
**Pull request by everett-toews**

### CODE REVIEW

**Comment by sivel** [comment]
This has been manually merged into the 'working' branch from the command line:

https://github.com/rackspace/pyrax/commit/e12b92937ff73a1c158553b084414c49658838fc

I can plan a release soon to ensure that this change gets pushed into master.

**Comment by sivel** [comment]
There are other things waiting in 'working' to be merged into master anyway, so this could be done soon.

**Comment by everett-toews** [comment]
@sivel What can we do about this reference?

https://github.com/rackspace/pyrax/blob/master/setup.py#L77

Is `author_email` absolutely necessary?

**Comment by sivel** [comment]
It is not really necessary, not really used in many places, and not exposed on pypi.  I can drop it from setup.py soon.

**Comment by everett-toews** [comment]
:+1:

**Comment by sivel** [comment]
This is actually resolved in master now.

**Pull request closed without merging**
