### PR TITLE
Added suppression interface

### PR DESCRIPTION
**Pull request by enver**
Per discussion in ticket #582

### CODE REVIEW

**Comment by briancurtin** [comment]
Per discussion in ticket #582, there are no plans to add this to Pyrax. I will talk to the other maintainer about this.

**Comment by briancurtin** [comment]
We're going to stick with the original message in #582 that we're not going to be adding this.

**Comment by enver** [comment]
So you are not going to implement this (just merge this!) in Pyrax and also can't give us any ETA when OpenStack SDK is going to be production ready! Nice...

**Comment by briancurtin** [comment]
To the first point: no, not merging it
To the second, there is a rough outline in the discussion you linked earlier. When I have a better timeline it will be provided.

**Comment by enver** [comment]
Ok, tnx...moving on to AWS :)

**Pull request closed without merging**
